### ISSUE TITLE
Add 3 simple pages to React UI

### ISSUE THREAD

**Issue by superquest** [arduino-bitcoin/simple_hardware_wallet#7]
TX history, send and receive.

Some mechanism to toggle between them. Perhaps a hamburger menu ...

**Comment by GustavoRSSilva** [comment]
@superquest making some tests with the hamburger menu. the problem of the hamburger menu, is that we only have 3 page. I was thinking of having a nice header that you could navigate thought the pages. Will save you one click in the end.

**Comment by stepansnigirev** [comment]
@GustavoRSSilva, @superquest, there are options.
1. Nelson made a sketch of the  [desktop screen with a sidebar](https://www.dropbox.com/s/w75vgv4iyi79i5v/Desktop_client.png?dl=0). Without the chart for now.
2. Make something simple like [these guys](https://github.com/lightninglabs/lightning-app) are doing - like a balance and two buttons (send and receive)
3. Tabs on top (like top nav menu) similar to what [Nelson did for the hackathon](https://www.dropbox.com/s/u1flf2w7n1r6wly/transactions.png?dl=0)

**Comment by GustavoRSSilva** [comment]
I really like Nelson version, the first one, @superquest @stepansnigirev can we agree to go with the one? I can pick this issue.

We would still miss a nice icon / favicon :).

**Comment by stepansnigirev** [comment]
@GustavoRSSilva, yes, I completely agree!
And I hope Nelson will continue and make us more nice screens =)

**Comment by GustavoRSSilva** [comment]
I think we can close this issue, will open a new one for the each component.
